[INFO ] 2019-04-25 16:34:12.073 [main] ConnectionPool - Connection pool created successfully
[INFO ] 2019-04-25 16:34:12.087 [main] ConnectionPool - Connection taken successfully
[INFO ] 2019-04-25 16:34:12.125 [main] UserDAOImplTest - User{login='Administrator', login='admin', password='21232f297a57a5a743894a0e4a801fc3', role=ADMIN}
[INFO ] 2019-04-25 16:34:35.791 [main] ConnectionPool - Connection pool created successfully
[INFO ] 2019-04-25 16:34:35.801 [main] ConnectionPool - Connection taken successfully
[INFO ] 2019-04-25 16:34:35.826 [main] UserDAOImplTest - User{login='Administrator', login='admin', password='21232f297a57a5a743894a0e4a801fc3', role=ADMIN}
[FATAL] 2019-04-25 19:24:51.749 [main] ConnectionPoolConfig - Connection pool will nowhere create. 
java.util.MissingResourceException: Can't find bundle for base login config/database, locale ru_RU
	at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2055) ~[?:?]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1689) ~[?:?]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1593) ~[?:?]
	at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1556) ~[?:?]
	at java.util.ResourceBundle.getBundle(ResourceBundle.java:857) ~[?:?]
	at com.epam.couriers.dao.connectionpool.ConnectionPoolConfig.<init>(ConnectionPoolConfig.java:24) [classes/:?]
	at com.epam.couriers.dao.connectionpool.ConnectionPool.<init>(ConnectionPool.java:34) [classes/:?]
	at com.epam.couriers.dao.connectionpool.ConnectionPool.getInstance(ConnectionPool.java:48) [classes/:?]
	at com.epam.couriers.dao.manager.TransactionManager.beginTransaction(TransactionManager.java:24) [classes/:?]
	at com.epam.couriers.service.impl.AdminServiceImpl.getAllCouriersRecords(AdminServiceImpl.java:19) [classes/:?]
	at com.epam.couriers.dao.impl.AdminDAOImplTest.testGetAllCouriersRecords(AdminDAOImplTest.java:16) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989) [testng-6.14.3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) [testng-6.14.3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) [testng-6.14.3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:648) [testng-6.14.3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:505) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1049) [testng-6.14.3.jar:?]
	at org.testng.TestNG.run(TestNG.java:1017) [testng-6.14.3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
[FATAL] 2019-04-25 19:27:38.018 [main] ConnectionPoolConfig - Connection pool will nowhere create. 
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key 
	at java.util.ResourceBundle.getObject(ResourceBundle.java:564) ~[?:?]
	at java.util.ResourceBundle.getString(ResourceBundle.java:521) ~[?:?]
	at com.epam.couriers.dao.connectionpool.ConnectionPoolConfig.<init>(ConnectionPoolConfig.java:29) [classes/:?]
	at com.epam.couriers.dao.connectionpool.ConnectionPool.<init>(ConnectionPool.java:34) [classes/:?]
	at com.epam.couriers.dao.connectionpool.ConnectionPool.getInstance(ConnectionPool.java:48) [classes/:?]
	at com.epam.couriers.dao.manager.TransactionManager.beginTransaction(TransactionManager.java:24) [classes/:?]
	at com.epam.couriers.service.impl.AdminServiceImpl.getAllCouriersRecords(AdminServiceImpl.java:19) [classes/:?]
	at com.epam.couriers.dao.impl.AdminDAOImplTest.testGetAllCouriersRecords(AdminDAOImplTest.java:16) [test-classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:583) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719) [testng-6.14.3.jar:?]
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989) [testng-6.14.3.jar:?]
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125) [testng-6.14.3.jar:?]
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109) [testng-6.14.3.jar:?]
	at org.testng.TestRunner.privateRun(TestRunner.java:648) [testng-6.14.3.jar:?]
	at org.testng.TestRunner.run(TestRunner.java:505) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:455) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunner.run(SuiteRunner.java:364) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52) [testng-6.14.3.jar:?]
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1137) [testng-6.14.3.jar:?]
	at org.testng.TestNG.runSuites(TestNG.java:1049) [testng-6.14.3.jar:?]
	at org.testng.TestNG.run(TestNG.java:1017) [testng-6.14.3.jar:?]
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73) [testng-plugin.jar:?]
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123) [testng-plugin.jar:?]
[INFO ] 2019-04-25 19:30:45.328 [main] ConnectionPool - Connection pool successfully created
[INFO ] 2019-04-25 19:30:46.571 [main] ConnectionPool - New connection created
